'use strict';(()=>{
const $=id=>document.getElementById(id),intro={id:'apresentacao',title:'Antes da primeira página',paragraphs:['Henrique sempre acreditou ser apenas um garoto comum.','Aos 18 anos, sua vida parecia seguir como a de qualquer outro jovem: família, jogos, responsabilidades, dúvidas sobre o futuro e sentimentos que ele ainda tentava compreender.','Até conhecer Hyejin.','O que começa com encontros inesperados, conversas, brincadeiras e sentimentos que crescem aos poucos transforma completamente o mundo de Henrique. Entre momentos felizes, perdas, escolhas e acontecimentos que parecem fugir de qualquer explicação, ele começa a perceber que talvez sua existência nunca tenha sido tão normal quanto imaginava.','Há algo escondido dentro dele. Algo antigo. Algo que nem mesmo Henrique conhece.','Mas até quando Henrique poderá continuar se chamando de um ser humano normal?']};
const ok=c=>c&&typeof c.id==='string'&&typeof c.title==='string'&&Array.isArray(c.paragraphs),chap=(window.BOOK_CHAPTERS||[]).filter(ok),extra=(window.BOOK_EXTRAS||[]).filter(ok),E=[intro,...chap,...extra],L=e=>e.number?'Capítulo '+String(e.number).padStart(2,'0'):e.id==='apresentacao'?'Apresentação':'Arte extra';
let S={};try{S=JSON.parse(localStorage.getItem('ushn-reader-v1'))||{}}catch{}let cur=Math.max(0,E.findIndex(e=>e.id===S.id)),fs=Number.isFinite(S.size)?S.size:20,night=S.night===true,art=Number.isInteger(S.art)?S.art:0;
const save=()=>{try{localStorage.setItem('ushn-reader-v1',JSON.stringify({id:E[cur].id,size:fs,night,art}))}catch{}},hash=()=>history.replaceState(null,'','#ler/'+E[cur].id);
function pref(){document.documentElement.style.setProperty('--reading-size',fs+'px');$('font-size').textContent=fs;$('smaller').disabled=fs<=16;$('larger').disabled=fs>=28;$('page').classList.toggle('night',night);$('theme').setAttribute('aria-pressed',String(night));$('theme').querySelector('span').textContent=night?'Papel':'Noite'}
function render(){let e=E[cur];$('reader-title').textContent=e.title;$('entry-label').textContent=L(e).toUpperCase();$('page-label').textContent=L(e).toUpperCase();$('reader-body').replaceChildren(...e.paragraphs.map(t=>{let p=document.createElement('p');p.textContent=t;return p}));$('reader-body').hidden=!e.paragraphs.length;$('page-number').textContent=L(e);$('previous').disabled=cur===0;$('next').disabled=cur===chap.length||cur===E.length-1;$('chapter-select').value=cur;$('reader-links').replaceChildren();let m=document.createElement('p');m.className='active-reading';m.textContent=L(e)+' · '+e.title;$('reader-links').append(m);let hm=!!e.images?.length;$('mode-manga').disabled=!hm;$('mode-manga-count').textContent=hm?' · '+e.images.length:'';$('reading-notice').hidden=!hm;$('reading-notice').textContent=hm?`Este capítulo também possui ${e.images.length} ${e.images.length>1?'páginas/artes':'página/arte'} no modo mangá.`:'';$('mode-story').classList.add('active');$('mode-manga').classList.remove('active');pref()}
function open(i){cur=i;art=0;render();save();hash();$('reader-title').focus({preventScroll:true});$('page').scrollIntoView({behavior:'instant',block:'start'})}
function row(e,i){let r=document.createElement('div');r.className='chapter-row chapter-row-actions';r.dataset.search=(L(e)+' '+e.title).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let n=document.createElement('span');n.className='chapter-number';n.textContent=e.number?String(e.number).padStart(2,'0'):'◇';let name=document.createElement('span');name.className='chapter-name';name.textContent=e.title;let sm=document.createElement('small');sm.textContent=e.images?.length?e.images.length+' página'+(e.images.length>1?'s/artes de mangá':'/arte de mangá'):(e.number?'Leitura em texto':'Apresentação');name.append(sm);let a=document.createElement('span');a.className='chapter-actions';let b=document.createElement('button');b.className='chapter-action';b.textContent='📖 Ler';b.onclick=()=>open(i);a.append(b);if(e.images?.length){let v=document.createElement('button');v.className='chapter-action manga-action';v.textContent='🎨 Ver mangá';v.onclick=()=>mOpen(i);a.append(v)}r.append(n,name,a);return r}
E.forEach((e,i)=>{(i<=chap.length?$('chapter-list'):$('extra-list')).append(row(e,i));let o=document.createElement('option');o.value=i;o.textContent=L(e)+' · '+e.title;$('chapter-select').append(o)});$('chapter-count').textContent=chap.length+' capítulos disponíveis';
$('chapter-search').oninput=()=>{let q=$('chapter-search').value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),c=0;[...$('chapter-list').children].forEach((r,i)=>{let hit=/^\d+$/.test(q)?E[i].number===+q:r.dataset.search.includes(q);r.hidden=!hit;if(hit)c++});$('search-status').textContent=q?(c?c+' resultado'+(c>1?'s':''):'Nenhum capítulo encontrado.'):''};
$('chapter-select').onchange=()=>open(+$('chapter-select').value);$('previous').onclick=()=>cur>0&&open(cur-1);$('next').onclick=()=>!$('next').disabled&&open(cur+1);$('smaller').onclick=()=>{fs=Math.max(16,fs-2);pref();save()};$('larger').onclick=()=>{fs=Math.min(28,fs+2);pref();save()};$('theme').onclick=()=>{night=!night;pref();save()};$('mode-story').onclick=()=>$('reader-body').scrollIntoView({behavior:'smooth'});$('mode-manga').onclick=()=>mOpen(cur);$('start').onclick=e=>{e.preventDefault();$('page').scrollIntoView({behavior:'smooth'})};
const cp=[],xp=[];E.forEach((e,ei)=>e.images?.forEach((im,ii)=>(ei<=chap.length?cp:xp).push({ei,ii,im})));let seq=[],pos=0,z=1,px=0,py=0,busy=false,pts=new Map(),sx=0,sy=0,spx=0,spy=0,pinch=0,pz=1,corner=0,cprog=0;
const sty=document.createElement('style');sty.textContent=`#manga-fullscreen{display:inline-flex!important;white-space:nowrap}#manga-top-next{border-color:#d9b87d66!important;color:#d9b87d!important}.manga-edge{opacity:.78!important;pointer-events:auto!important;font-weight:700}.manga-edge:disabled{opacity:.16!important;pointer-events:none!important}.manga-stage.is-zoomed .manga-edge{opacity:0!important;pointer-events:none!important}.manga-corner{position:absolute;width:54px;height:54px;z-index:11;pointer-events:none;opacity:.32}.manga-corner:before{content:'';position:absolute;inset:0;border:2px solid #d9b87d88;border-right:0;border-bottom:0}.ctl{top:8px;left:8px}.ctr{top:8px;right:8px;transform:scaleX(-1)}.cbl{bottom:8px;left:8px;transform:scaleY(-1)}.cbr{bottom:8px;right:8px;transform:scale(-1)}.manga-stage.is-zoomed .manga-corner{display:none}.manga-shell:fullscreen,.manga-shell.cinema{position:fixed;inset:0;width:100vw;height:100dvh;display:block;background:#030406;z-index:2147483647}.manga-shell:fullscreen .manga-stage,.manga-shell.cinema .manga-stage{position:absolute;inset:0}.manga-shell:fullscreen .manga-book,.manga-shell.cinema .manga-book{width:100vw;height:100dvh;max-height:100dvh;padding:64px 45px 48px}.manga-shell:fullscreen .manga-topbar,.manga-shell.cinema .manga-topbar{position:absolute;inset:0 0 auto;z-index:30;background:linear-gradient(#05070aee,#05070aaa,transparent);border:0}.manga-shell:fullscreen .manga-bottombar,.manga-shell.cinema .manga-bottombar{position:absolute;inset:auto 0 0;z-index:30;background:linear-gradient(transparent,#05070aaa,#05070aee);border:0}@media(max-width:800px){#manga-fullscreen{display:inline-flex!important;font-size:0}#manga-fullscreen:after{content:'⛶';font-size:18px}#manga-top-next{font-size:0}#manga-top-next:after{content:'→';font-size:18px}.manga-edge{bottom:54px!important;top:auto!important;transform:none!important}.manga-shell:fullscreen .manga-book,.manga-shell.cinema .manga-book{padding:54px 8px 40px}}`;document.head.append(sty);
let topNext=document.createElement('button');topNext.id='manga-top-next';topNext.textContent='Próxima →';topNext.setAttribute('aria-label','Próxima página');document.querySelector('.manga-controls').insertBefore(topNext,$('manga-close'));['ctl','ctr','cbl','cbr'].forEach(c=>{let x=document.createElement('span');x.className='manga-corner '+c;$('manga-stage').append(x)});$('manga-fullscreen').textContent='⛶ Tela cheia';
const page=()=>seq[pos],target=d=>seq[pos+d],sequence=i=>i<=chap.length?cp:xp;
function nav(){let p=page(),a=target(-1),n=target(1),ac=a&&a.ei!==p.ei,nc=n&&n.ei!==p.ei;$('manga-prev').disabled=!a;$('manga-next').disabled=!n;$('manga-prev').textContent=a?(ac?'← Capítulo anterior':'← Página anterior'):'← Início';$('manga-next').textContent=n?(nc?'Próximo capítulo →':'Próxima página →'):'Fim do mangá';topNext.disabled=!n;topNext.textContent=n?(nc?'Próximo capítulo →':'Próxima →'):'Fim'}
function src(){let p=page();if(!p)return;cur=p.ei;art=p.ii;let e=E[cur],im=p.im;$('manga-image').src=im.src;$('manga-image').alt=L(e)+' — '+im.title;$('manga-under-image').src=im.src;$('manga-chapter').textContent=L(e).toUpperCase();$('manga-title').textContent=e.title;$('manga-position').textContent=`Página ${pos+1} de ${seq.length} · ${L(e)} · ${art+1}/${e.images.length}`;nav();save();hash()}
function tf(){let b=$('manga-book');b.style.transform=`translate3d(${px}px,${py}px,0) scale(${z})`;$('manga-zoom').value=Math.round(z*100);$('manga-zoom-label').textContent=Math.round(z*100)+'%';$('manga-zoom-reset').textContent=Math.round(z*100)+'%';let can=z<=1.15;$('manga-stage').classList.toggle('can-turn',can);$('manga-stage').classList.toggle('is-zoomed',!can);$('manga-pan-hint').textContent=can?'Puxe um canto, arraste para o lado ou clique em Próxima página.':'Zoom ativo · arraste a imagem. Volte perto de 100% para virar a página.'}
function zoom(v){z=Math.max(1,Math.min(3,v));if(z<=1.05)px=py=0;tf()}function reset(){z=1;px=py=0;tf()}
function mOpen(i){let e=E[i];if(!e.images?.length)return;seq=sequence(i);let found=seq.findIndex(p=>p.ei===i&&p.ii===(i===cur?art:0));if(found<0)found=seq.findIndex(p=>p.ei===i);pos=Math.max(0,found);reset();src();if(!$('manga-dialog').open)$('manga-dialog').showModal();document.body.classList.add('dialog-open');requestAnimationFrame(()=>$('manga-stage').focus())}
function under(d){let t=target(d);if(!t)return null;$('manga-under-image').src=t.im.src;return t}
function finish(np){pos=np;let sh=$('manga-sheet');sh.classList.remove('turn-next','turn-prev');sh.style.cssText='';src();reset();busy=false}
function turn(d){if(busy||z>1.15||!target(d))return;let np=pos+d;under(d);let u=$('manga-under-image'),sh=$('manga-sheet');busy=true;let go=()=>{sh.classList.remove('turn-next','turn-prev');void sh.offsetWidth;sh.classList.add(d>0?'turn-next':'turn-prev');let done=false,f=()=>{if(done)return;done=true;finish(np)};sh.addEventListener('animationend',f,{once:true});setTimeout(f,760)};u.complete&&u.naturalWidth?go():(u.onload=go,u.onerror=go,setTimeout(go,220))}
function cdir(e){if(z>1.15||busy)return 0;let r=$('manga-stage').getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,s=Math.min(150,r.width*.2),c=Math.min(180,r.height*.28);if(!(y<c||y>r.height-c))return 0;if(x>r.width-s&&target(1))return 1;if(x<s&&target(-1))return-1;return 0}
function cmove(e){if(!corner)return;let r=$('manga-stage').getBoundingClientRect(),d=corner>0?sx-e.clientX:e.clientX-sx;cprog=Math.max(0,Math.min(1,d/Math.max(120,r.width*.42)));let sh=$('manga-sheet'),a=(corner>0?-1:1)*cprog*168;sh.style.transition='none';sh.style.transformOrigin=corner>0?'left center':'right center';sh.style.transform=`rotateY(${a}deg) scale(${1-cprog*.018})`;sh.style.opacity=1-cprog*.55;sh.style.filter=`drop-shadow(${corner>0?28:-28}px 15px 30px #000c) brightness(${1-cprog*.28})`}
function cend(commit){if(!corner)return;let d=corner,np=pos+d,sh=$('manga-sheet');corner=0;sh.style.transition='transform .34s ease,opacity .34s ease,filter .34s ease';if(commit&&np>=0&&np<seq.length){busy=true;sh.style.transform=`rotateY(${d>0?-180:180}deg) scale(.98)`;sh.style.opacity=0;setTimeout(()=>finish(np),350)}else{sh.style.transform='rotateY(0)';sh.style.opacity=1;setTimeout(()=>{sh.style.cssText=''},350)}cprog=0}
$('manga-prev').onclick=()=>turn(-1);$('manga-next').onclick=()=>turn(1);topNext.onclick=()=>turn(1);$('manga-zoom-out').onclick=()=>zoom(z-.25);$('manga-zoom-in').onclick=()=>zoom(z+.25);$('manga-zoom-reset').onclick=reset;$('manga-zoom').oninput=()=>zoom(+$('manga-zoom').value/100);
$('manga-close').onclick=()=>{$('manga-dialog').close()};$('manga-dialog').addEventListener('close',()=>{document.body.classList.remove('dialog-open');if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});document.querySelector('.manga-shell').classList.remove('cinema');render();reset()});
async function full(){let s=document.querySelector('.manga-shell');try{if(document.fullscreenElement)await document.exitFullscreen();else if(s.requestFullscreen)await s.requestFullscreen({navigationUI:'hide'});else s.classList.toggle('cinema')}catch{s.classList.toggle('cinema')}}$('manga-fullscreen').onclick=full;document.addEventListener('fullscreenchange',()=>{$('manga-fullscreen').textContent=document.fullscreenElement?'⛶ Sair':'⛶ Tela cheia'});
function dist(){let a=[...pts.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}
$('manga-stage').onpointerdown=e=>{if(e.target.closest('button,input'))return;$('manga-stage').setPointerCapture?.(e.pointerId);pts.set(e.pointerId,{x:e.clientX,y:e.clientY});sx=e.clientX;sy=e.clientY;spx=px;spy=py;if(pts.size===1&&z<=1.15){corner=cdir(e);cprog=0;if(corner)under(corner)}if(pts.size===2){if(corner)cend(false);pinch=dist();pz=z}};
$('manga-stage').onpointermove=e=>{if(!pts.has(e.pointerId))return;pts.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pts.size===2){zoom(pz*dist()/Math.max(1,pinch));return}if(corner){cmove(e);return}if(z>1.05){px=spx+e.clientX-sx;py=spy+e.clientY-sy;tf()}};
function pend(e){let one=pts.size===1&&pts.has(e.pointerId),dx=e.clientX-sx;pts.delete(e.pointerId);if(corner)cend(cprog>.2||Math.abs(dx)>64);else if(one&&z<=1.15&&Math.abs(dx)>80)turn(dx<0?1:-1);if(pts.size<2)pinch=0}$('manga-stage').onpointerup=pend;$('manga-stage').onpointercancel=pend;$('manga-stage').ondblclick=e=>{if(!e.target.closest('button,input'))zoom(z>1.15?1:2)};$('manga-dialog').onkeydown=e=>{if(e.key==='ArrowRight')turn(1);else if(e.key==='ArrowLeft')turn(-1);else if(e.key==='+'||e.key==='=')zoom(z+.25);else if(e.key==='-')zoom(z-.25);else if(e.key==='0')reset()};
let hid=location.hash.startsWith('#ler/')?location.hash.slice(5):null;if(hid){let i=E.findIndex(e=>e.id===hid);if(i>=0)cur=i}render();})();